version: "3.9"

services:
  go-app:
    container_name: go-server
    build:
      context: .
      target: final
    environment:
      DATABASE_URL: "host=go_db user=postgres password=8008 dbname=sitesb port=5432 sslmode=disable"
    ports:
      - 4000:4000
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: 8008
      POSTGRES_USER: postgres
      POSTGRES_DB: sitesb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
