name: Deploy to Server

on:
  push:
    branches:
      - main # Укажите вашу ветку, например, main или master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh                # Создание директории .ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy # Установка разрешений на ключ
          eval $(ssh-agent -s)           # Запуск ssh-agent
          ssh-add ~/.ssh/github_deploy

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 89.104.70.77 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh root@89.104.70.77 'bash -s' < ./deploy.sh
